apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iokz5f6ui-java-quarkus
  janus-idp.io/tekton: iokz5f6ui-java-quarkus
  backstage.io/kubernetes-id: iokz5f6ui-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iokz5f6ui-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
